hehehe

diff --git a/rice b/rice
--- a/rice
+++ b/rice
@@ -1,4 +1,5 @@
 #!/bin/dash
+# vim: filetype=sh
 #
 # http://github.com/mitchweaver/bin
 #
@@ -6,32 +7,35 @@
 #
 
 usage() {
-    printf "%s\n%s\n%s\n\n%s\n%s\n%s\n%s\n" \
-        "Usage: " \
-        "------------------------------------" \
-        "$ rice \"\$wallpaper_path\"" \
-        "Options:" \
-        "------------------------------------" \
-        "--no-kill    -    do not kill progs" \
-        "--light      -    make a light theme"
-    exit 0
+	printf "%s\n%s\n%s\n\n%s\n%s\n%s\n%s\n" \
+		"Usage: " \
+		"------------------------------------" \
+		"$ rice \"\$wallpaper_path\"" \
+		"Options:" \
+		"------------------------------------" \
+		"--no-kill    -    do not kill progs" \
+		"--light      -    make a light theme"
+	exit 0
 }
 [ $# -eq 0 ] && usage
 
-while [ $# -gt 0 ] ; do
-    case "$1" in
-        --light|-l)   LIGHT=true ;;
-        --no-kill|-n) nokill=true ;;
-        --help|-h)    usage ;;
-        *) path="$1"
-    esac
-    shift
+while [ $# -gt 0 ]; do
+	case "$1" in
+	--light | -l) LIGHT=true ;;
+	--no-kill | -n) nokill=true ;;
+	--help | -h) usage ;;
+	*) path="$1" ;;
+	esac
+	shift
 done
 
 [ ! -f "$path" ] && usage
 
 wall_path="${HOME}/var/tmp/wall"
-cp "$path" "$wall_path" > /dev/null || { echo "Unable to copy to $wall_path" ; exit 1 ; }
+cp "$path" "$wall_path" >/dev/null || {
+	echo "Unable to copy to $wall_path"
+	exit 1
+}
 
 pkill -9 xwinwrap
 
@@ -40,8 +44,8 @@ pkill -9 xwinwrap
 # or a cinemagraph. Find out what it is,
 # and launch with the appropriate program.
 case "$(basename $(file -b -i -L ${wall_path}))" in
-    *png*|*jpg*|*jpeg*) feh --bg-fill --no-fehbg ${wall_path} & ;;
-    *gif*|*webm*|*mp4*|*mkv*) mpvbg ${wall_path} &
+*png* | *jpg* | *jpeg*) feh --bg-fill --no-fehbg ${wall_path} &;;
+*gif* | *webm* | *mp4* | *mkv*) mpvbg ${wall_path} &;;
 esac
 
 [ -n "$LIGHT" ] && wal -qnli "$wall_path" || wal -qni "$wall_path"
@@ -49,19 +53,19 @@ esac
 cat ${HOME}/.cache/wal/sequences
 
 # Generate web browser startpage css
-if type sassc > /dev/null 2>&1 ; then
-    spage=${HOME}/usr/startpage
-    sassc $spage/scss/style.scss $spage/style.css
-fi > /dev/null 2>&1 &
+if type sassc >/dev/null 2>&1; then
+	spage=${HOME}/usr/startpage
+	sassc $spage/scss/style.scss $spage/style.css
+fi >/dev/null 2>&1 &
 
 {
-    # Recomp suckless tools
-    dir="${HOME}/etc/suckless"
-    ${HOME}/bin/recomp $dir/dwm $dir/st $dir/tabbed -- > /dev/null 2>&1
+	# Recomp suckless tools
+	dir="${HOME}/etc/suckless"
+	${HOME}/bin/recomp $dir/dwm $dir/st $dir/tabbed -- >/dev/null 2>&1
 
-    # recopy to tmpfs
-    ${HOME}/bin/copy-tmpfs
+	# recopy to tmpfs
+	${HOME}/bin/copy-tmpfs
 } &
 
 pkill -9 bar
-${HOME}/bin/bar > /dev/null 2>&1 &
+${HOME}/bin/bar >/dev/null 2>&1 &
